mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: online.shixun.project.pojo
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3305/chat?serverTimezone=UTC&characterEncoding=UTF-8&tinyInt1isBit=false
    username: root
  jpa:
    database: mysql
  thymeleaf:
    cache: false
